[transcription]
# beste Qualität
model_name = "large-v3"
language = "de"
output_dir = "output"

[mail]
smtp_host = "smtp.gmail.com"
smtp_port = 465
smtp_use_ssl = true
from_name = "Spracherkennung by sIn"
subject_prefix = "[Transkript]"

[logging]
log_dir = "logs"
level = "INFO"
