name: Docs Build Check

on:
  pull_request:
    branches:
      - main

jobs:
  docs-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
    
      - name: Install dependencies
        run: |
          pip install pdoc
    
      - name: Build documentation with pdoc
        run: |
          PYTHONPATH=src pdoc trsc \
            --docformat markdown \
            --logo assets/logo2.png \
            --logo-link https://github.com/OnPlastic/Audio_Transcription \
            --e trsc=https://github.com/OnPlastic/Audio_Transcription/blob/main/src/trsc/ \
            