name: Pages Deploy

on:
  push:
    branches:
      - main

jobs:
  pages-deploy
    runs-on: ubuntu-latest

    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      
      - name: Install dependencies
        run: |
          pip install pdoc

      - name: Build documentation with pdoc
        run: |
          PYTHONPATH=src pdoc trsc \
            --docformat markdown \
            --logo assets/logo2.png \
            --logo-link https://github.com/OnPlastic/Audio_Transcription \
            --e trsc=https://github.com/OnPlastic/Audio_Transcription/blob/man/src/trsc/ \
            -o docs/api
      
      - name: Commit and push documentation
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add docs/api

          git diff --cached --quiet || git commit -m "docs: update API documentation"

          git push